INSERT INTO service (sever_id, name, position, state) VALUES (1, 'Acceso para discapacitados', 1, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (2, 'Aire acondicionado', 2, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (3, 'Ambiente romántico', 3, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (4, 'Bar', 4, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (5, 'Baños para discapacitados', 5, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (6, 'Buffet (Consultar Horarios)', 6, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (7, 'Catering', 7, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (8, 'Corcho libre (Consultar Restricciones)', 8, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (9, 'Delivery', 9, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (10, 'Descorche (Consultar Restricciones)', 10, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (11, 'Estacionamiento', 11, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (12, 'Estufas', 12, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (13, 'Eventos corporativos', 13, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (14, 'Happy hour (Consultar Horarios)', 14, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (15, 'Menú ejecutivo', 15, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (16, 'Menú para niños', 16, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (17, 'Mesas al aire libre', 17, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (18, 'Música de fondo', 18, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (19, 'Música en vivo (Consultar Horarios)', 19, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (20, 'Platos a la carta', 20, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (21, 'Promoción para el cumpleañero (Consultar Promoción)', 21, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (22, 'Reservas', 22, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (23, 'Show en vivo (Consultar Horarios)', 23, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (24, 'Sala de espera', 24, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (25, 'Silla para bebés / niños', 25, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (26, 'Salón privado', 26, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (27, 'Terraza', 27, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (28, 'Valet Parking', 28, 1);
INSERT INTO service (sever_id, name, position, state) VALUES (29, 'Wi Fi', 29, 1);

INSERT INTO pay (sever_id, name_file, position, state) VALUES (1, 'cash', 1, 1);
INSERT INTO pay (sever_id, name_file, position, state) VALUES (2, 'american_express', 2, 1);
INSERT INTO pay (sever_id, name_file, position, state) VALUES (3, 'diners_club', 3, 1);
INSERT INTO pay (sever_id, name_file, position, state) VALUES (4, 'euro', 4, 1);
INSERT INTO pay (sever_id, name_file, position, state) VALUES (5, 'paypal', 5, 1);
INSERT INTO pay (sever_id, name_file, position, state) VALUES (6, 'maestro', 6, 1);
INSERT INTO pay (sever_id, name_file, position, state) VALUES (7, 'mastercard', 7, 1);
INSERT INTO pay (sever_id, name_file, position, state) VALUES (8, 'visa', 8, 1);
